services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - '${MYSQL_PORT}:3306'
    expose:
      - '3306'
    volumes:
      - database-volume:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - './apps/symfony/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/symfony/:/usr/src/app'
    restart: on-failure
    environment:
      DATABASE_URL: 'mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=8.0.24'
      MAILER_DSN: 'smtp://:@mailer:1025'
    user: ${LOCAL_USER}
    depends_on:
      - mailer

  node:
    image: node:latest
    volumes:
      - './apps/symfony/:/usr/src/app'

  mailer:
    image: mailhog/mailhog:latest
    restart: on-failure
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  database-volume:
