controllers:
    resource: ../src
    type: annotation

app_confirm_account:
    path: /confirmation-inscription

homepage:
    path: /
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'homepage.html.twig'

kernel:
    resource: ../src/Kernel.php
    type: annotation
